export const profileDataList = [
  { src: "/profile.svg", alt: "profile icon", label: "이름", value: "장성우" },
  {
    src: "/calendar.svg",
    alt: "calendar icon",
    label: "생년월일",
    value: "97.03.05",
  },
  { src: "/gps.svg", alt: "gps icon", label: "위치", value: "서울 동작구" },
  {
    src: "/mail.svg",
    alt: "mail icon",
    label: "메일",
    value: "devlasbe@gmail.com",
  },
];

export const projectDataList = [
  {
    title: "오픈프차",
    period: "2024.11~",
    desc: "공정거래위원회의 가맹사업 정보공개서를 기반으로 창업 전, 프랜차이즈 본사 정보, 브랜드의 매출, 가맹점 수, 인테리어 금액, 창업 비용 정보를 편리하게 확인할 수 있습니다.",
    subDesc: [
      "NextJS와 NestJS를 이용해 풀스택 개발",
      "차트를 활용한 각종 데이터 시각화",
      "데스크톱 및 모바일 디바이스에 대응",
      "swagger-typescript-api를 이용해 백엔드 API - 프론트엔드 간 타입 동기화",
      "Playwright + Docker를 이용한 E2E 테스트 환경 구축",
      "Private Docker Repository 구축 후 Github Action으로 배포 자동화",
      "PM2를 이용해 백엔드 배포 환경을 구성하여 클러스터 모드, 분산 서비스, 모니터링 환경 구축",
    ],
    imageList: [
      "/project_images/openfranchise1.webp",
      "/project_images/openfranchise2.webp",
      "/project_images/openfranchise3.webp",
      "/project_images/openfranchise4.webp",
    ],
    stack: [
      "NextJS",
      "tailwind",
      "shadcn/ui",
      "Recharts",
      "Playwright",
      "Vercel",
      "NestJS",
      "Prisma",
      "PostgreSQL",
      "Docker",
      "PM2",
    ],
    link: "https://www.openfranchise.kr/",
    readme: "https://github.com/devlasbe/open-franchise-frontend",
  },
  {
    title: "안성재 요리 평가 GPT",
    period: "2024.10",
    desc: "흑백요리사 안성재 쉐프의 말투로 음식평가 결과를 출력하는 밈 프로젝트",
    subDesc: [
      "openai gpt-4o-mini 모델을 이용하여 결과 출력",
      "많게는 하루에 400 이상의 페이지뷰 기록",
      "기획-개발-출시까지 12시간 내 완료",
    ],
    imageList: ["/project_images/ansungjae1.jpg", "/project_images/ansungjae2.jpg"],
    stack: ["TypeScript", "Nextjs", "tailwind", "shadcn/ui", "openai", "vercel"],
    link: "https://ansungjae-gpt.vercel.app/",
    readme: "https://github.com/devlasbe/ansungjae-gpt",
  },
  {
    title: "포트폴리오",
    period: "2024.10",
    desc: "포트폴리오 용도로 제작한 웹사이트",
    subDesc: [
      "github action에서 제공하는 runner로 앱, 도커 빌드 후 ssh를 통해 원격으로 물리 서버에 배포",
      "기존에 개발한 애니메이션 라이브러리 컴포넌트 적극 사용",
      "반응형 설계로 데스크톱 및 스마트폰 대응",
    ],
    imageList: ["/project_images/portfolio1.jpg", "/project_images/portfolio2.jpg"],
    stack: ["TypeScript", "Nextjs", "tailwind", "Firebase", "docker", "github-action"],
    link: "https://lasbe.kr/",
    readme: "https://github.com/devlasbe/lasbe-homepage",
  },
  {
    title: "LINGMO",
    period: "2023.06 - 2023.07",
    desc: "여러 URL 링크를 모아주는 서비스",
    subDesc: [
      "github action runner를 물리 서버에 설치 하여 배포 자동화",
      "컴포넌트 단위의 애니메이션 개발",
      "반응형 설계로 데스크톱 및 스마트폰 대응",
    ],
    imageList: ["/project_images/lingmo1.webp", "/project_images/lingmo2.webp"],
    stack: ["TypeScript", "React", "Recoil", "styled-components", "Firebase", "github-action"],
    readme: "https://lasbe.tistory.com/180",
  },
  // {
  //   title: "닥터플렉스",
  //   period: "2023.08 - 2023.11",
  //   desc: "React-Native로 개발된 앱의 신규 개발 및 최적화 업무 수행",
  //   subDesc: [
  //     "신규 이벤트 배너, Screen 개발",
  //     "질환별 자문하기 개발",
  //     "의료 정보 제공 서비스 개발",
  //     "안드로이드 ScrollView 이미지 최적화 기능 개발",
  //   ],
  //   imageList: ["/project_images/doctorflex1.jpg"],
  //   stack: ["TypeScript", "React-Native"],
  //   link: "https://doctorflex.co.kr/",
  // },
  {
    title: "Going",
    period: "2022.04 - 2022.05",
    desc: "숙박 플랫폼 프로젝트",
    subDesc: [
      "기획, 디자인, F/E, B/E, DB 설계 등 프로젝트에 전반적으로 관여",
      "유저, 사업자, 관리자로 나뉜 플랫폼 형태의 서비스",
    ],
    imageList: [
      "/project_images/going1.jpg",
      "/project_images/going2.jpg",
      "/project_images/going3.jpg",
      "/project_images/going4.jpg",
    ],
    stack: ["Java", "Spring", "MyBatis", "Oracle", "JQuery"],
    readme: "https://lasbe.tistory.com/130",
  },
  {
    title: "InstaAuto",
    period: "2021.04",
    desc: "인스타그램 계정 마케팅을 위한 자동화 프로그램",
    subDesc: [
      "파이썬과 셀레니움을 이용한 웹 데이터 크롤링",
      "PyQT를 이용해 GUI 개발",
      "3일만에 목표치인 팔로워 1,000명 달성",
    ],
    imageList: ["/project_images/InstaAuto1.jpg", "/project_images/InstaAuto2.jpg", "/project_images/InstaAuto3.jpg"],
    stack: ["Python", "PyQT"],
    readme: "https://github.com/devlasbe/InstaAuto",
  },
];
