export const project = {
  OPEN_FRANCHISE: {
    title: "오픈프차",
    period: "2024.11~",
    desc: "공정거래위원회의 가맹사업 정보공개서를 기반으로 창업 전, 프랜차이즈 본사 정보, 브랜드의 매출, 가맹점 수, 인테리어 금액, 창업 비용 정보를 편리하게 확인할 수 있습니다.",
    subDesc: [
      "일 평균 150~200명 접속",
      "NextJS와 NestJS를 이용해 풀스택 개발",
      "차트를 활용한 각종 데이터 시각화",
      "데스크톱 및 모바일 디바이스에 대응",
      "swagger-typescript-api를 이용해 백엔드 API - 프론트엔드 간 타입 동기화",
      "Playwright + Docker를 이용한 E2E 테스트 환경 구축",
      "Private Docker Repository 구축 후 Github Action으로 배포 자동화",
      "PM2를 이용해 백엔드 배포 환경을 구성하여 클러스터 모드, 분산 서비스, 모니터링 환경 구축",
    ],
    stack: [
      "NextJS",
      "tailwind",
      "shadcn/ui",
      "Recharts",
      "Playwright",
      "Vercel",
      "NestJS",
      "Prisma",
      "PostgreSQL",
      "Docker",
      "PM2",
    ],
    link: "https://www.openfranchise.kr/",
    readme: "https://github.com/devlasbe/open-franchise-frontend",
  },
  SHAPIC: {
    title: "Shapic",
    period: "2025.04~",
    desc: "SNS에 최적화된 이미지 리사이징 및 최적화 데스크톱 앱입니다. 33개의 SNS 프리셋을 기반으로 이미지를 빠르게 변환하고, EXIF 메타데이터 프레임 오버레이 기능을 제공합니다.",
    subDesc: [
      "Instagram, Facebook, X, YouTube, TikTok, LinkedIn 등 33개 SNS 프리셋 내장",
      "7가지 리사이즈 모드 지원 (cover, contain, 비율, 장변, 단변, 너비, 높이)",
      "JPEG/WebP 출력 및 품질 조절",
      "EXIF 메타데이터 프레임 오버레이 (카메라 정보를 흰색 테두리로 표시)",
      "배치 처리 및 실시간 진행률 표시",
      "실시간 미리보기 (디바운스 적용)",
      "커스텀 프리셋 생성 기능",
      "macOS (arm64/x64) 및 Windows 지원",
    ],
    stack: [
      "Electron",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "Sharp",
      "Electron Vite",
    ],
    link: undefined,
    readme: "https://github.com/devlasbe/shapic",
  },
  KOREA_DEBT_CLOCK: {
    title: "K-머니",
    period: "2026.07~",
    desc: "대한민국 국가부채(국가채무)가 실시간으로 늘어나는 모습을 보여주는 대시보드입니다. 연 1회 갱신되는 공식 통계를 초당 단위로 보간해 실시간 카운터로 시각화합니다.",
    subDesc: [
      "연 1회 갱신되는 공식 통계를 초당 단위로 보간해 실시간으로 올라가는 카운터로 시각화",
      "GDP 대비 채무비율·국민 1인당 빚·연도별 추이·정부 재정운용계획 전망(2029년까지) 제공",
      "e-나라지표·KOSIS·한국은행 ECOS·Frankfurter(ECB) 공공·무료 데이터를 교차 검증해 통합",
      "국가부채라는 딱딱한 통계를 한눈에 체감되는 대시보드로 재구성",
    ],
    stack: ["Vite", "React", "TypeScript", "Tailwind CSS", "Recharts", "Vercel"],
    link: "https://dashboard.lasbe.kr",
    readme: "https://github.com/devlasbe/korea-debt-clock",
  },
};
